### ISSUE TITLE
OPENSSL.SSL.Error: 'SSL routines' 'ca md too weak'

### ISSUE THREAD

**Issue by Raugo** [kabutor/RecoverOfflineCertificate#1]
I get this error when I try to obtain the certificates using the new method.

> Traceback (most recent call last):
  File "pkcs12_dpapi_export.py", line 126, in <module>
    check_associate_cert_with_private_key(certificate,k)
  File "pkcs12_dpapi_export.py", line 32, in check_associate_cert_with_private_key
    context.use_certificate(cert_obj)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenSSL/SSL.py", line 971, in use_certificate
    _raise_current_error()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', '', 'ca md too weak')]

**Comment by kabutor** [comment]
Been browsing, seems that the certificate is using a very weak algorithm, try adding in the line number 30 a line, you should have it like this:
```
    context = OpenSSL.SSL.Context(OpenSSL.SSL.TLSv1_METHOD)
    context.set_ciphers('ALL:@SECLEVEL=0')
    context.use_privatekey(private_key_obj)
   
```

**Comment by Raugo** [comment]
Don't works but almost. Openssl don't have set_cyphers but have set_cypher_list and is basically the same. 
With this code I sucefully extracted the certs

`    context = OpenSSL.SSL.Context(OpenSSL.SSL.TLSv1_METHOD)
    context.set_cipher_list('ALL:@SECLEVEL=0')
    context.use_privatekey(private_key_obj)`

Show a warning because the use of strings is now deprecated but works. Thank you.

**Comment by kabutor** [comment]
Glad to see it works, I can't test that without your AppData files, and that can be a privacy problem.

I'll add that as a comment in case someone else have the same issue, Thanks.
